GET http://localhost:8080/orders HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmlhbmFAbWFpbC5jb20iLCJpYXQiOjE2ODk2OTc4MDgsImV4cCI6MTY4OTcwMTQwOCwic3ViIjoiOCJ9.xg_ER4kenjnBsDmoEI6Fuf-2rhR63JZPer3Rf2QF7Z0

# {
#     "name": "Prueba 7",
#     "price": 500,
#     "type": "Breakfast"
# }

# {
# "id":"6"
# }

# {
#     "name": "Pruebacinco",
#     "email": "waiter7@mail.com",
#     "password": "123456",
#     "role": "waiter"
# }



# "type": "Lunch & dinner"