GET http://localhost:8080/orders HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmlhbmFAbWFpbC5jb20iLCJpYXQiOjE2ODkzNDM5MTgsImV4cCI6MTY4OTM0NzUxOCwic3ViIjoiOCJ9.KW-9AjILSENivK4cHg50jeZBKeGmpqYa7lNlpHY5jfU

# {
#     "name": "Prueba 7",
#     "price": 500,
#     "type": "Breakfast"
# }

# {
# "id":"6"
# }

# {
#     "name": "Pruebacinco",
#     "email": "waiter7@mail.com",
#     "password": "123456",
#     "role": "waiter"
# }



# "type": "Lunch & dinner"